# DIABOLO


In [1]:
# Import all libraries needed for the tutorial

# General syntax to import specific functions in a library: 
##from (library) import (specific library function)
#from  pandas import DataFrame, read_csv

# General syntax to import a library but no functions: 
##import (library) as (give the library a nickname/alias)

import pandas as pd
import numpy as np

#vous pouvez modifier cette option à votre guise
pd.options.display.max_rows = 10

                   
Location_csv = 'd:\diabolo.csv'
xnames=['ALLURE','DATE_COURSE','CO_DISTANCE','CO_NB','CO_PRIX','HIPPO','IDCOURSE','IDPARTCIPANT','PAR_age','PAR_ARRIVE',
'PAR_CARRIERE','PAR_CARRIERE_Q','PAR_CLASSE_AGE','PAR_CORDE','PAR_COTEDER','PAR_ENT_ECART_GAGNANT','PAR_ENT_RAPPORT_GAGNANT_M',
'PAR_ENT_RAPPORT_GANGANT','PAR_ENT_REU_PLACE','PAR_ENT_REUSSITE_GAGNE','PAR_ENT_VICTOIRE','PAR_GAIN','pAR_JOC_ECART_GAGNANT',
'PAR_JOC_ECART_PLACE','PAR_JOC_NB_COURSE','PAR_JOC_PLACE_3P','pAR_JOC_RAPPORT_GAGNANT_M','PAR_JOC_REU_PLACE','pAR_JOC_REUSSITE_GAGNE',
'pAR_JOC_VICTOIRE','PAR_NP','PAR_NUM','PAR_PLACE','PAR_PLACE_Q','PAR_REUSSITE_3P','PAR_REUSSITE_GAGNE','PAR_REUSSITE_QUINTE','PAR_RUESSITE_PLACE','autostart','cendre','grande_piste','sable_fibre','dirt','FIN_ligne']
    
df=pd.read_csv (Location_csv, sep=';',names=xnames,nrows=10000,skipinitialspace=True,encoding='Latin-1')

df=df.groupby('ALLURE')     
df=df.get_group(1) 

#Suppression de la collone TROT
df.drop(["ALLURE"], axis=1, inplace=True)

#Suppression de la collone TROT
df.drop(["FIN_ligne"], axis=1, inplace=True)

#Suppression de la collone TROT
df.drop(["DATE_COURSE"], axis=1, inplace=True)

#Suppression de la collone TROT
df.drop(["IDPARTCIPANT"], axis=1, inplace=True)

#Suppression de la collone TROT
df.drop(["HIPPO"], axis=1, inplace=True)

#Suppression de la collone TROT
df.drop(["IDCOURSE"], axis=1, inplace=True)

#xnames=['CO_DISTANCE','CO_NB','CO_PRIX','HIPPO','IDCOURSE','PAR_age','PAR_ARRIVE',
#'PAR_CARRIERE','PAR_CARRIERE_Q','PAR_CLASSE_AGE','PAR_CORDE','PAR_COTEDER','PAR_ENT_ECART_GAGNANT','PAR_ENT_RAPPORT_GAGNANT_M',
#'PAR_ENT_RAPPORT_GANGANT','PAR_ENT_REU_PLACE','PAR_ENT_REUSSITE_GAGNE','PAR_ENT_VICTOIRE','PAR_GAIN','pAR_JOC_ECART_GAGNANT',
#'PAR_JOC_ECART_PLACE','PAR_JOC_NB_COURSE','PAR_JOC_PLACE_3P','pAR_JOC_RAPPORT_GAGNANT_M','PAR_JOC_REU_PLACE','pAR_JOC_REUSSITE_GAGNE',
#'pAR_JOC_VICTOIRE','PAR_NP','PAR_PLACE','PAR_PLACE_Q','PAR_REUSSITE_3P','PAR_REUSSITE_GAGNE','PAR_REUSSITE_QUINTE','PAR_RUESSITE_PLACE','autostart','cendre','grande_piste','sable_fibre','dirt']
   
#Transformer une colonne en un index dans un dataframe
#df = df.set_index('IDPARTCIPANT')

#affichage des premiere lignes du jeu de données
df.head()



CO_DISTANCE  CO_NB  CO_PRIX  PAR_age  PAR_ARRIVE  PAR_CARRIERE  \
9             0     17    90000        5          99            41   
10            0     17    90000        6           4            58   
11            0     17    90000        6           2            41   
12            0     17    90000        6           1            64   
13            0     17    90000        5          99            10   

    PAR_CARRIERE_Q  PAR_CLASSE_AGE  PAR_CORDE  PAR_COTEDER  ...   PAR_PLACE_Q  \
9                5           44456          0           32  ...             0   
10               3           34229          0            8  ...             2   
11               9           40630          0           36  ...             4   
12               2           39671          0            6  ...             0   
13               1           48270          0           10  ...             0   

    PAR_REUSSITE_3P  PAR_REUSSITE_GAGNE  PAR_REUSSITE_QUINTE  \
9          0.292683            0.121951              0.00000   
10         0.396552            0.155172              0.00000   
11         0.585366            0.317073              0.04878   
12         0.500000            0.218750              0.03125   
13         0.800000            0.600000              0.00000   

    PAR_RUESSITE_PLACE  autostart  cendre  grande_piste  sable_fibre  dirt  
9             0.170732          1       1             1            0     0  
10            0.241379          1       1             1            0     0  
11            0.268293          1       1             1            0     0  
12            0.281250          1       1             1            0     0  
13            0.200000          1       1             1            0     0  

[5 rows x 38 columns]

In [2]:
# trvail sur les courses de trot (allure=1)
print(df.shape)


(5473, 38)


In [3]:
#enumeration des colonnes
df.columns


Index(['CO_DISTANCE', 'CO_NB', 'CO_PRIX', 'PAR_age', 'PAR_ARRIVE',
       'PAR_CARRIERE', 'PAR_CARRIERE_Q', 'PAR_CLASSE_AGE', 'PAR_CORDE',
       'PAR_COTEDER', 'PAR_ENT_ECART_GAGNANT', 'PAR_ENT_RAPPORT_GAGNANT_M',
       'PAR_ENT_RAPPORT_GANGANT', 'PAR_ENT_REU_PLACE',
       'PAR_ENT_REUSSITE_GAGNE', 'PAR_ENT_VICTOIRE', 'PAR_GAIN',
       'pAR_JOC_ECART_GAGNANT', 'PAR_JOC_ECART_PLACE', 'PAR_JOC_NB_COURSE',
       'PAR_JOC_PLACE_3P', 'pAR_JOC_RAPPORT_GAGNANT_M', 'PAR_JOC_REU_PLACE',
       'pAR_JOC_REUSSITE_GAGNE', 'pAR_JOC_VICTOIRE', 'PAR_NP', 'PAR_NUM',
       'PAR_PLACE', 'PAR_PLACE_Q', 'PAR_REUSSITE_3P', 'PAR_REUSSITE_GAGNE',
       'PAR_REUSSITE_QUINTE', 'PAR_RUESSITE_PLACE', 'autostart', 'cendre',
       'grande_piste', 'sable_fibre', 'dirt'],
      dtype='object')

In [4]:
#appel de la fonction sur l'ensemble des colonnes du DataFrame
#axis = 0 ==> chaque colonne sera transmise à la fonction operation()
#la selection select_dtypes() permet d'exclure les variables non numériques

resultat = df.select_dtypes(exclude=['object']).apply(operation,axis=0)
resultat

NameError: name 'operation' is not defined

In [5]:
# restriction de l'ensemble de données
# selection des lignes avec des arrivées 1-5
colonnes = ['PAR_ARRIVE']
df.loc[df['PAR_ARRIVE']<=5,colonnes] 



PAR_ARRIVE
10             4
11             2
12             1
15             3
16             5
...          ...
9987           2
9992           5
9993           3
9997           4
9999           5

[1987 rows x 1 columns]

In [6]:
#gagnant
#sélection des gagnants


df_gagnant = df.loc[df['PAR_ARRIVE']==1] 
df_gagnant

CO_DISTANCE  CO_NB  CO_PRIX  PAR_age  PAR_ARRIVE  PAR_CARRIERE  \
12              0     17    90000        6           1            64   
40              0     18    70000        8           1            80   
44              0     12    44000        4           1            26   
57              0     11    40000        6           1            53   
72              0     16    40000        5           1            36   
...           ...    ...      ...      ...         ...           ...   
9807            0     13     5000        5           1            71   
9817            0     16     5000        4           1            34   
9835            0     16     5000        4           1            35   
9980            0     15    21000        3           1            26   
9986            0     14    17000        4           1            30   

      PAR_CARRIERE_Q  PAR_CLASSE_AGE  PAR_CORDE  PAR_COTEDER  ...   \
12                 2           39671          0            6  ...    
40                18           27238          0           28  ...    
44                 1            8175          0            5  ...    
57                 2            9620          0            9  ...    
72                 1            9354          0            9  ...    
...              ...             ...        ...          ...  ...    
9807               0            3190          0            3  ...    
9817               0            1676          0            8  ...    
9835               0             536          0           12  ...    
9980               0            2060          0           31  ...    
9986               0            2907          0           10  ...    

      PAR_PLACE_Q  PAR_REUSSITE_3P  PAR_REUSSITE_GAGNE  PAR_REUSSITE_QUINTE  \
12              0         0.500000            0.218750              0.03125   
40              4         0.300000            0.162500              0.00000   
44              1         0.500000            0.269231              0.00000   
57              1         0.245283            0.132076              0.00000   
72              1         0.500000            0.250000              0.00000   
...           ...              ...                 ...                  ...   
9807            0         0.338028            0.112676              0.00000   
9817            0         0.411765            0.147059              0.00000   
9835            0         0.314286            0.114286              0.00000   
9980            0         0.230769            0.115385              0.00000   
9986            0         0.166667            0.066667              0.00000   

      PAR_RUESSITE_PLACE  autostart  cendre  grande_piste  sable_fibre  dirt  
12              0.281250          1       1             1            0     0  
40              0.137500          0       1             1            0     0  
44              0.230769          0       1             1            0     0  
57              0.113208          0       1             1            0     0  
72              0.250000          0       1             1            0     0  
...                  ...        ...     ...           ...          ...   ...  
9807            0.225352          1       0             0            0     0  
9817            0.264706          1       0             0            0     0  
9835            0.200000          1       0             0            0     0  
9980            0.115385          1       0             0            0     0  
9986            0.100000          1       0             0            0     0  

[397 rows x 38 columns]

In [7]:
#gagnant
#sélection des chevaux dans les 5 premiers


df_gagnant = df.loc[df['PAR_ARRIVE']<=5] 
df_gagnant


CO_DISTANCE  CO_NB  CO_PRIX  PAR_age  PAR_ARRIVE  PAR_CARRIERE  \
10              0     17    90000        6           4            58   
11              0     17    90000        6           2            41   
12              0     17    90000        6           1            64   
15              0     17    90000        6           3            36   
16              0     17    90000        6           5            56   
...           ...    ...      ...      ...         ...           ...   
9987            0     14    17000        4           2            33   
9992            0     14    17000        4           5            11   
9993            0     14    17000        4           3            49   
9997            0     14    17000        4           4            33   
9999            0     16    21000        8           5            90   

      PAR_CARRIERE_Q  PAR_CLASSE_AGE  PAR_CORDE  PAR_COTEDER  ...   \
10                 3           34229          0            8  ...    
11                 9           40630          0           36  ...    
12                 2           39671          0            6  ...    
15                 8           40470          0            2  ...    
16                12           36820          0           27  ...    
...              ...             ...        ...          ...  ...    
9987               0            2590          0            6  ...    
9992               0            2525          0           11  ...    
9993               0            2410          0           20  ...    
9997               0            1915          0          173  ...    
9999               1           12887          0            8  ...    

      PAR_PLACE_Q  PAR_REUSSITE_3P  PAR_REUSSITE_GAGNE  PAR_REUSSITE_QUINTE  \
10              2         0.396552            0.155172              0.00000   
11              4         0.585366            0.317073              0.04878   
12              0         0.500000            0.218750              0.03125   
15              4         0.500000            0.166667              0.00000   
16              8         0.517857            0.107143              0.00000   
...           ...              ...                 ...                  ...   
9987            0         0.333333            0.121212              0.00000   
9992            0         0.181818            0.181818              0.00000   
9993            0         0.204082            0.040816              0.00000   
9997            0         0.151515            0.030303              0.00000   
9999            0         0.277778            0.122222              0.00000   

      PAR_RUESSITE_PLACE  autostart  cendre  grande_piste  sable_fibre  dirt  
10              0.241379          1       1             1            0     0  
11              0.268293          1       1             1            0     0  
12              0.281250          1       1             1            0     0  
15              0.333333          1       1             1            0     0  
16              0.410714          1       1             1            0     0  
...                  ...        ...     ...           ...          ...   ...  
9987            0.212121          1       0             0            0     0  
9992            0.000000          1       0             0            0     0  
9993            0.163265          1       0             0            0     0  
9997            0.121212          1       0             0            0     0  
9999            0.155556          1       0             0            0     0  

[1987 rows x 38 columns]

In [8]:
df_gagnant=df_gagnant[df_gagnant.PAR_GAIN >0]
df_gagnant







CO_DISTANCE  CO_NB  CO_PRIX  PAR_age  PAR_ARRIVE  PAR_CARRIERE  \
10              0     17    90000        6           4            58   
11              0     17    90000        6           2            41   
12              0     17    90000        6           1            64   
15              0     17    90000        6           3            36   
16              0     17    90000        6           5            56   
...           ...    ...      ...      ...         ...           ...   
9987            0     14    17000        4           2            33   
9992            0     14    17000        4           5            11   
9993            0     14    17000        4           3            49   
9997            0     14    17000        4           4            33   
9999            0     16    21000        8           5            90   

      PAR_CARRIERE_Q  PAR_CLASSE_AGE  PAR_CORDE  PAR_COTEDER  ...   \
10                 3           34229          0            8  ...    
11                 9           40630          0           36  ...    
12                 2           39671          0            6  ...    
15                 8           40470          0            2  ...    
16                12           36820          0           27  ...    
...              ...             ...        ...          ...  ...    
9987               0            2590          0            6  ...    
9992               0            2525          0           11  ...    
9993               0            2410          0           20  ...    
9997               0            1915          0          173  ...    
9999               1           12887          0            8  ...    

      PAR_PLACE_Q  PAR_REUSSITE_3P  PAR_REUSSITE_GAGNE  PAR_REUSSITE_QUINTE  \
10              2         0.396552            0.155172              0.00000   
11              4         0.585366            0.317073              0.04878   
12              0         0.500000            0.218750              0.03125   
15              4         0.500000            0.166667              0.00000   
16              8         0.517857            0.107143              0.00000   
...           ...              ...                 ...                  ...   
9987            0         0.333333            0.121212              0.00000   
9992            0         0.181818            0.181818              0.00000   
9993            0         0.204082            0.040816              0.00000   
9997            0         0.151515            0.030303              0.00000   
9999            0         0.277778            0.122222              0.00000   

      PAR_RUESSITE_PLACE  autostart  cendre  grande_piste  sable_fibre  dirt  
10              0.241379          1       1             1            0     0  
11              0.268293          1       1             1            0     0  
12              0.281250          1       1             1            0     0  
15              0.333333          1       1             1            0     0  
16              0.410714          1       1             1            0     0  
...                  ...        ...     ...           ...          ...   ...  
9987            0.212121          1       0             0            0     0  
9992            0.000000          1       0             0            0     0  
9993            0.163265          1       0             0            0     0  
9997            0.121212          1       0             0            0     0  
9999            0.155556          1       0             0            0     0  

[1588 rows x 38 columns]

In [9]:
#MESURES d'association entre variables quantitatives : coefficient de corrélation
import numpy as np

len(df_gagnant)

UneSerie = pd.Series(df_gagnant['PAR_ARRIVE'])                       # Une DATAFRAME est composée de serie

#Suppression de la collone TROT
df_gagnant.drop(["PAR_ARRIVE"], axis=1, inplace=True)



    

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':


In [10]:
#df_gagnant = df_gagnant.frame(df_gagnant,UneSerie)
df_gagnant['PAR_ARRIVE'] = UneSerie
#print(df_gagnant)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  


In [11]:
###########################################################################################################
#Modèles de régressions linéaires multiples                                                               #
# mesurer l 'influence de plusieurs variables sur le fait qu 'un participant soit parmi les 5 premiers    #
###########################################################################################################

# Variables possible

# Utilisation du module statsmodels
# xnames=['DATE_COURSE','CO_DISTANCE','CO_NB','CO_PRIX','HIPPO','IDCOURSE','IDPARTCIPANT','PAR_age','PAR_ARRIVE',
# 'PAR_CARRIERE','PAR_CARRIERE_Q','PAR_CLASSE_AGE','PAR_CORDE','PAR_COTEDER','PAR_ENT_ECART_GAGNANT','PAR_ENT_RAPPORT_GAGNANT_M',
# 'PAR_ENT_RAPPORT_GANGANT','PAR_ENT_REU_PLACE','PAR_ENT_REUSSITE_GAGNE','PAR_ENT_VICTOIRE','PAR_GAIN','pAR_JOC_ECART_GAGNANT',
# 'PAR_JOC_ECART_PLACE','PAR_JOC_NB_COURSE','PAR_JOC_PLACE_3P','pAR_JOC_RAPPORT_GAGNANT_M','PAR_JOC_REU_PLACE','pAR_JOC_REUSSITE_GAGNE',
# 'pAR_JOC_VICTOIRE','PAR_NP','PAR_NUM','PAR_PLACE','PAR_PLACE_Q','PAR_REUSSITE_3P','PAR_REUSSITE_GAGNE','PAR_REUSSITE_QUINTE','PAR_RUESSITE_PLACE','autostart','cendre','grande_piste','sable_fibre','dirt','FIN_ligne']
   
# Préparation de la table de donées pour la régression :
##serie_de1 = pd.Series(1, index = range(len(df_gagnant))) 
##df_1 = pd.DataFrame(serie_de1,columns=['const'])
##df_1

##df_gagnant = df_gagnant.frame(df_gagnant,serie_de1)

pd.options.mode.chained_assignment = None

#df_gagnant['Const'] = pd.Series(1,index=df_gagnant.index)

#x = df.drop(['PAR_ARRIVE'], axis=1) # Construction des variables explicatives en supprimant la colonne MEDV
#print(x)


                              





In [12]:
#Utilisation du module sklearn

data = np.matrix(df_gagnant)
data






matrix([[  0.00000000e+00,   1.70000000e+01,   9.00000000e+04, ...,
           0.00000000e+00,   0.00000000e+00,   4.00000000e+00],
        [  0.00000000e+00,   1.70000000e+01,   9.00000000e+04, ...,
           0.00000000e+00,   0.00000000e+00,   2.00000000e+00],
        [  0.00000000e+00,   1.70000000e+01,   9.00000000e+04, ...,
           0.00000000e+00,   0.00000000e+00,   1.00000000e+00],
        ..., 
        [  0.00000000e+00,   1.40000000e+01,   1.70000000e+04, ...,
           0.00000000e+00,   0.00000000e+00,   3.00000000e+00],
        [  0.00000000e+00,   1.40000000e+01,   1.70000000e+04, ...,
           0.00000000e+00,   0.00000000e+00,   4.00000000e+00],
        [  0.00000000e+00,   1.60000000e+01,   2.10000000e+04, ...,
           0.00000000e+00,   0.00000000e+00,   5.00000000e+00]])

In [13]:
X= data[:,0:36] # # Sélectionner toutes les variable sauf la dernière colonne
X # X matrice des varibale explicatives 



matrix([[  0.00000000e+00,   1.70000000e+01,   9.00000000e+04, ...,
           1.00000000e+00,   1.00000000e+00,   0.00000000e+00],
        [  0.00000000e+00,   1.70000000e+01,   9.00000000e+04, ...,
           1.00000000e+00,   1.00000000e+00,   0.00000000e+00],
        [  0.00000000e+00,   1.70000000e+01,   9.00000000e+04, ...,
           1.00000000e+00,   1.00000000e+00,   0.00000000e+00],
        ..., 
        [  0.00000000e+00,   1.40000000e+01,   1.70000000e+04, ...,
           0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
        [  0.00000000e+00,   1.40000000e+01,   1.70000000e+04, ...,
           0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
        [  0.00000000e+00,   1.60000000e+01,   2.10000000e+04, ...,
           0.00000000e+00,   0.00000000e+00,   0.00000000e+00]])

In [14]:
y=data[:,37]  # Y vecteur de la variable a prédire
y


matrix([[ 4.],
        [ 2.],
        [ 1.],
        ..., 
        [ 3.],
        [ 4.],
        [ 5.]])

In [29]:
# Utilisation du module cross_validation de scikit-learn (sklearn) pour
# subdiviser l'échantillon en un échantillon d'apprentissage et de
# validation


from sklearn import cross_validation
#subdivision des données – éch.test = 300 ; éch.app = 768 – éch.test = 468

X_app,X_test,y_app,y_test = cross_validation.train_test_split(X,y,test_size = 500,random_state=0)
print(X_app.shape,X_test.shape,y_app.shape,y_test.shape)

(1088, 36) (500, 36) (1088, 1) (500, 1)


In [35]:
#importer la classe LogisticRegression
from sklearn.linear_model import LogisticRegression

#création d'une instance de la classe
lr = LogisticRegression()

#exécution de l'instance sur les données d'apprentissage c.à-d.
#construction du modèle prédictif
modele =  lr.fit(X_app,y_app)
#les sortie
#les sorties
print(modele.coef_,modele.intercept_)



[[  0.00000000e+00  -8.32088010e-03  -1.83106952e-06  -3.24523533e-03
   -3.28506976e-03   8.70238919e-03  -6.54603114e-07   0.00000000e+00
   -5.44956590e-02   3.19174028e-03  -1.44976723e-02   0.00000000e+00
   -5.96239166e-06   3.23655229e-05   4.29804375e-03   2.78085160e-07
   -2.92960966e-03  -4.78274928e-03  -1.76460257e-03   4.92675685e-03
    2.65271388e-03  -1.14248949e-04  -6.91444460e-05  -2.06314935e-04
    0.00000000e+00  -3.51828609e-03  -7.90441792e-03   6.64406889e-04
    5.46391126e-04   9.78153490e-04   4.02268623e-05  -4.31762721e-04
   -3.36544505e-04   1.52415856e-04   1.54233106e-04   0.00000000e+00]
 [  0.00000000e+00  -1.95052723e-02  -7.04865493e-06  -4.72538784e-03
   -7.07626672e-03   4.50246351e-03   1.09635322e-06   0.00000000e+00
   -1.39196835e-02  -1.10953661e-02  -3.83133762e-03   0.00000000e+00
   -3.93139186e-04  -1.12986717e-04   2.53837428e-03  -3.77567736e-07
   -5.62254873e-03  -3.16239782e-03   2.34891085e-03  -5.62113007e-03
    1.25179937e-04 

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [36]:
#prédiction sur l'échantillon test
y_pred = modele.predict(X_test)

In [37]:
#importation de metrics - utilisé pour les mesures de performances
from sklearn import metrics

#matrice de confusion: confrontation entre Y observé sur l’échantillon de test et la prédiction
cm = metrics.confusion_matrix(y_test,y_pred)
print(cm)




[[45 23  4  6  6]
 [45 24  7 10 14]
 [31 30  8 11 13]
 [23 25 12 12 43]
 [23 26 13 11 35]]


In [33]:
#taux de succès
acc = metrics.accuracy_score(y_test,y_pred)
print(acc) # 0.793 = (184 + 54)/ (184 + 17 + 45 + 54)

0.248


In [34]:
#taux d'erreur
err = 1.0 - acc
print(err) # 0.206 = 1.0 – 0.793


0.752
